name: Release

on:
  push:
    tags:
      - '*'  # Triggers on every tag

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: xkcd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Change if needed

      - name: Build for Linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o xkcd-linux-amd64

      - name: Build for macOS amd64
        run: GOOS=darwin GOARCH=amd64 go build -o xkcd-darwin-amd64

      - name: Build for macOS ARM64
        run: GOOS=darwin GOARCH=arm64 go build -o xkcd-darwin-arm64

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            xkcd/xkcd-linux-amd64
            xkcd/xkcd-darwin-amd64
            xkcd/xkcd-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
