name: Release

on:
  push:
    tags:
      - '*'  # Triggers on every tag

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build for Linux amd64
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/xkcd-linux-amd64 .

      - name: Build for Linux arm64
        run: |
          GOOS=linux GOARCH=arm64 go build -o dist/xkcd-linux-arm64 .

      - name: Build for macOS amd64
        run: |
          GOOS=darwin GOARCH=amd64 go build -o dist/xkcd-darwin-amd64 .

      - name: Build for macOS ARM64
        run: |
          GOOS=darwin GOARCH=arm64 go build -o dist/xkcd-darwin-arm64 .

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/xkcd-linux-amd64
            dist/xkcd-linux-arm64
            dist/xkcd-darwin-amd64
            dist/xkcd-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
